server:
  port: 3000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: rid6ZPjGfNTsGKlDGkQX97ECXJxLuzYa
            client-secret: LWLSQtLRcBgWDZCSB40Ur71BLWbRRtSy_n7irunr4Jc4vvI7tIgRfQK4KkAfrYo2
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://symbiocreation.auth0.com/

fablat.landing.uri: https://fab.lat