spring.profiles.active: dev

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: rid6ZPjGfNTsGKlDGkQX97ECXJxLuzYa
            client-secret: LWLSQtLRcBgWDZCSB40Ur71BLWbRRtSy_n7irunr4Jc4vvI7tIgRfQK4KkAfrYo2
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://symbiocreation.auth0.com/

fablat.landing.uri: https://fab.lat


---
spring.config.activate.on-profile: dev
server.port: 3000
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.auth0.example: TRACE

---
spring.config.activate.on-profile: prod
server:
  port: 5000
#  use-forward-headers: true
  forward-headers-strategy: framework
logging:
  level:
    root: ERROR
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    com.auth0.example: TRACE